/**
 * 已知 AI 服务清单
 *
 * 每条记录包含：
 * - name:       服务名称（展示用）
 * - domains:    相关域名（用于网络扫描和浏览器历史匹配）
 * - processNames: 本地进程名（用于进程扫描，适用于桌面/本地AI工具）
 * - category:   服务类别
 * - riskLevel:  默认风险等级（'high' | 'medium' | 'low'）
 * - description: 说明
 */

'use strict';

const AI_SERVICES = [
  // ── 国际对话AI ─────────────────────────────────────────────────────────────
  {
    name: 'ChatGPT',
    domains: ['chat.openai.com', 'api.openai.com', 'chatgpt.com', 'oai.azure.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: 'OpenAI 旗舰对话AI，广泛用于文本生成与代码辅助',
  },
  {
    name: 'Claude',
    domains: ['claude.ai', 'api.anthropic.com', 'anthropic.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: 'Anthropic 对话AI，以长上下文处理见长',
  },
  {
    name: 'Gemini',
    domains: ['gemini.google.com', 'bard.google.com', 'generativelanguage.googleapis.com', 'ai.google.dev'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: 'Google Gemini / Bard 对话AI',
  },
  {
    name: 'Microsoft Copilot',
    domains: ['copilot.microsoft.com', 'bing.com/chat', 'sydney.bing.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'medium',
    description: 'Microsoft Copilot / Bing AI',
  },
  {
    name: 'Perplexity',
    domains: ['perplexity.ai', 'api.perplexity.ai'],
    processNames: [],
    category: 'search',
    riskLevel: 'medium',
    description: 'AI驱动的搜索引擎',
  },
  {
    name: 'Character.AI',
    domains: ['character.ai', 'beta.character.ai'],
    processNames: [],
    category: 'chat',
    riskLevel: 'medium',
    description: '角色扮演对话AI',
  },
  {
    name: 'Poe',
    domains: ['poe.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'medium',
    description: 'Quora Poe AI聚合平台',
  },
  {
    name: 'Grok',
    domains: ['x.ai', 'grok.x.ai'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: 'xAI Grok 对话AI',
  },

  // ── 图像生成AI ─────────────────────────────────────────────────────────────
  {
    name: 'Midjourney',
    domains: ['midjourney.com', 'www.midjourney.com'],
    processNames: [],
    category: 'image',
    riskLevel: 'high',
    description: 'AI图像生成服务（通过Discord使用）',
  },
  {
    name: 'DALL-E',
    domains: ['labs.openai.com'],
    processNames: [],
    category: 'image',
    riskLevel: 'high',
    description: 'OpenAI DALL-E 图像生成',
  },
  {
    name: 'Stable Diffusion Online',
    domains: ['stability.ai', 'api.stability.ai', 'dreamstudio.ai', 'stablediffusionweb.com'],
    processNames: [],
    category: 'image',
    riskLevel: 'medium',
    description: 'Stability AI 图像生成服务',
  },
  {
    name: 'Adobe Firefly',
    domains: ['firefly.adobe.com'],
    processNames: [],
    category: 'image',
    riskLevel: 'medium',
    description: 'Adobe AI图像生成',
  },
  {
    name: 'Canva AI',
    domains: ['canva.com'],
    processNames: ['canva'],
    category: 'image',
    riskLevel: 'low',
    description: 'Canva AI设计工具',
  },

  // ── 代码AI ─────────────────────────────────────────────────────────────────
  {
    name: 'GitHub Copilot',
    domains: ['api.githubcopilot.com', 'copilot-proxy.githubusercontent.com', 'copilot-telemetry.githubusercontent.com'],
    processNames: [],
    category: 'code',
    riskLevel: 'medium',
    description: 'GitHub AI代码补全（通过IDE插件使用）',
  },
  {
    name: 'Cursor',
    domains: ['cursor.sh', 'api2.cursor.sh'],
    processNames: ['cursor', 'Cursor'],
    category: 'code',
    riskLevel: 'high',
    description: 'AI驱动的代码编辑器，会上传代码至云端',
  },
  {
    name: 'Codeium',
    domains: ['codeium.com', 'api.codeium.com', 'backend.codeium.com'],
    processNames: [],
    category: 'code',
    riskLevel: 'medium',
    description: 'Codeium AI代码补全',
  },
  {
    name: 'Tabnine',
    domains: ['www.tabnine.com', 'api.tabnine.com'],
    processNames: ['tabnine'],
    category: 'code',
    riskLevel: 'medium',
    description: 'Tabnine AI代码补全',
  },

  // ── AI平台/API ──────────────────────────────────────────────────────────────
  {
    name: 'Hugging Face',
    domains: ['huggingface.co', 'api-inference.huggingface.co'],
    processNames: [],
    category: 'platform',
    riskLevel: 'medium',
    description: 'Hugging Face AI模型托管与推理平台',
  },
  {
    name: 'Cohere',
    domains: ['api.cohere.com', 'cohere.ai'],
    processNames: [],
    category: 'platform',
    riskLevel: 'medium',
    description: 'Cohere NLP API',
  },
  {
    name: 'Replicate',
    domains: ['replicate.com', 'api.replicate.com'],
    processNames: [],
    category: 'platform',
    riskLevel: 'medium',
    description: 'Replicate AI模型运行平台',
  },
  {
    name: 'Groq',
    domains: ['api.groq.com', 'groq.com'],
    processNames: [],
    category: 'platform',
    riskLevel: 'medium',
    description: 'Groq 高速LLM推理API',
  },
  {
    name: 'Mistral AI',
    domains: ['api.mistral.ai', 'mistral.ai'],
    processNames: [],
    category: 'platform',
    riskLevel: 'medium',
    description: 'Mistral AI 开源LLM API',
  },
  {
    name: 'Together AI',
    domains: ['api.together.xyz', 'together.ai'],
    processNames: [],
    category: 'platform',
    riskLevel: 'medium',
    description: 'Together AI 开源模型云推理',
  },

  // ── 国内AI服务 ──────────────────────────────────────────────────────────────
  {
    name: '文心一言',
    domains: ['yiyan.baidu.com', 'aip.baidubce.com', 'qianfan.baidubce.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: '百度文心一言对话AI',
  },
  {
    name: '讯飞星火',
    domains: ['xinghuo.xfyun.cn', 'spark-api.xf-yun.cn', 'spark-api.cn-huabei-1.xf-yun.cn'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: '科大讯飞星火认知大模型',
  },
  {
    name: '通义千问',
    domains: ['qianwen.aliyun.com', 'dashscope.aliyuncs.com', 'tongyi.aliyun.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: '阿里云通义千问大模型',
  },
  {
    name: 'Kimi',
    domains: ['kimi.moonshot.cn', 'api.moonshot.cn', 'moonshot.cn'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: 'Moonshot AI Kimi 长文本对话',
  },
  {
    name: '豆包',
    domains: ['doubao.com', 'ark.cn-beijing.volces.com', 'www.doubao.com'],
    processNames: ['doubao', 'Doubao'],
    category: 'chat',
    riskLevel: 'high',
    description: '字节跳动豆包AI助手',
  },
  {
    name: 'DeepSeek',
    domains: ['deepseek.com', 'api.deepseek.com', 'chat.deepseek.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: 'DeepSeek 大模型对话',
  },
  {
    name: '智谱清言 / ChatGLM',
    domains: ['chatglm.cn', 'open.bigmodel.cn', 'bigmodel.cn'],
    processNames: [],
    category: 'chat',
    riskLevel: 'high',
    description: '智谱AI ChatGLM 大模型',
  },
  {
    name: '天工AI',
    domains: ['tiangong.cn', 'model-tiangong.cn'],
    processNames: [],
    category: 'chat',
    riskLevel: 'medium',
    description: '昆仑万维天工AI对话',
  },
  {
    name: 'Hailuo AI / Minimax',
    domains: ['hailuo.ai', 'api.minimax.chat', 'minimaxi.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'medium',
    description: 'MiniMax 海螺AI',
  },
  {
    name: '360 AI',
    domains: ['ai.360.cn', '360aiwei.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'medium',
    description: '360 AI 安全大模型',
  },
  {
    name: '商汤SenseChat',
    domains: ['sensechat.com', 'nova.sensetime.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'medium',
    description: '商汤科技SenseChat',
  },
  {
    name: '百川大模型',
    domains: ['baichuan-ai.com', 'api.baichuan-ai.com'],
    processNames: [],
    category: 'platform',
    riskLevel: 'medium',
    description: '百川智能大模型API',
  },
  {
    name: '腾讯混元',
    domains: ['hunyuan.tencent.com', 'yuanqi.tencent.com'],
    processNames: [],
    category: 'chat',
    riskLevel: 'medium',
    description: '腾讯混元大模型',
  },
  {
    name: '讯飞输入法AI',
    domains: ['shurufa.app', 'voicecloud.cn'],
    processNames: ['iFlyIME', 'iflyrec'],
    category: 'productivity',
    riskLevel: 'low',
    description: '讯飞输入法AI功能',
  },

  // ── 本地AI工具（进程扫描）──────────────────────────────────────────────────
  {
    name: 'Ollama',
    domains: ['localhost:11434', '127.0.0.1:11434'],
    processNames: ['ollama', 'ollama.exe', 'Ollama'],
    category: 'local_llm',
    riskLevel: 'medium',
    description: '本地大模型运行框架（Ollama），可能在本机运行未审批模型',
  },
  {
    name: 'LM Studio',
    domains: ['localhost:1234', '127.0.0.1:1234'],
    processNames: ['LM Studio', 'lmstudio', 'lmstudio.exe'],
    category: 'local_llm',
    riskLevel: 'medium',
    description: 'LM Studio 本地大模型运行工具',
  },
  {
    name: 'GPT4All',
    domains: ['localhost:4891', '127.0.0.1:4891'],
    processNames: ['gpt4all', 'gpt4all.exe', 'GPT4All'],
    category: 'local_llm',
    riskLevel: 'medium',
    description: 'GPT4All 离线大模型工具',
  },
  {
    name: 'LocalAI',
    domains: ['localhost:8080', '127.0.0.1:8080'],
    processNames: ['local-ai', 'localai', 'LocalAI'],
    category: 'local_llm',
    riskLevel: 'medium',
    description: 'LocalAI 开源本地AI服务',
  },
  {
    name: 'Open WebUI',
    domains: ['localhost:3000', '127.0.0.1:3000', 'localhost:8080'],
    processNames: ['open-webui'],
    category: 'local_llm',
    riskLevel: 'medium',
    description: 'Open WebUI 本地LLM前端',
  },
  {
    name: 'Msty',
    domains: ['localhost:8942', '127.0.0.1:8942'],
    processNames: ['Msty', 'msty'],
    category: 'local_llm',
    riskLevel: 'medium',
    description: 'Msty 本地AI客户端',
  },
  {
    name: 'Jan',
    domains: ['localhost:1337', '127.0.0.1:1337'],
    processNames: ['Jan', 'jan.exe'],
    category: 'local_llm',
    riskLevel: 'medium',
    description: 'Jan 开源本地AI对话工具',
  },
];

module.exports = { AI_SERVICES };
