ALTER TABLE role ADD COLUMN IF NOT EXISTS allow_self_register BOOLEAN DEFAULT FALSE;
ALTER TABLE role ADD COLUMN IF NOT EXISTS is_system BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS user_role (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
